### ISSUE TITLE
MAU false error - "AutoUpdate cannot connect to the update server",

### ISSUE THREAD

**Issue by scottlep** [pbowden-msft/MAUCacheAdmin#25]
We are seeing an issue when using local cache/manifest servers and MAU version 14.16.19101301, where if there are no available updates MAU shows a false error that "AutoUpdate cannot connect to the update server", instead of some kind of message saying that there are no updates available. The servers are 100% reachable, so this definitely seems to be a false error. Any suggestions on how to correct this or how to correctly show that there are no updates available?

Thanks,
Scott

![Screen Shot 2019-11-04 at 9 28 27 AM](https://user-images.githubusercontent.com/4138295/68128554-f0a7b780-fee5-11e9-9911-4a548fd270ec.png)

**Comment by pbowden-msft** [comment]
Hi @scottlep I think the first step would be to inspect the network traffic to see if the MAU client is getting 5xx responses from the manifest server. My personal favorite tool for looking at this is Charles Proxy. Hope this helps!

**Comment by scottlep** [comment]
We have no issue getting updates when there are actually updates available. The issue is when all updates (ones that have been made available on our cache/manifest server) have been completed and someone opens MAU and tries to manually check for updates they are shown the error that "AutoUpdate cannot connect to the update server". I have tested this repeatedly by back-dating apps, allowing them to be auto-updated, or manually checking for updates with MAU and the updates are available with no errors about not being able to connect to the update server, but once all updates are done, MAU reports it cannot connect to the update server. This is why I believe it is a false error and should actually be reporting that no updates are available.

Thanks,
Scott

**Comment by pbowden-msft** [comment]
@scottlep I just ran MAU 4.16 under Charles Proxy, and it looks like 4.16 and later require a 200 OK HTTP response for all files that it's looking for, otherwise it'll return that generic 'cannot connect to the update server' error. What's probably happening in your case is that MAU has a registered app for which it can't find any collateral on your server, thus resulting in a 404. For example, if MAU has an app registration for ONDR18, then it'll look on your manifest server for 0409ONDR18-chk.xml. Based on the version number embedded in that file, it might want to look further for 0409ONDR18.cat and 0409ONDR18.xml.
The easiest way to find the offending file(s) is to use Charles Proxy.

**Comment by scottlep** [comment]
That was it. Had to copy/move the ONDR files from Legacy to Production, then MAU reports "all apps are up to date". Thanks as always for you help and expertise Paul!

~Scott

**Comment by pbowden-msft** [comment]
@scottlep Great! Glad you got it sorted out.
